# ------------------------------------------------------------------
# SSH key pair — generated by Terraform. The private key is exported
# as a (sensitive) output so you can paste it into GitHub secrets.
# ------------------------------------------------------------------
resource "tls_private_key" "deploy" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "deploy" {
  key_name   = "${var.project_name}-deploy"
  public_key = tls_private_key.deploy.public_key_openssh
}

# ------------------------------------------------------------------
# Latest Ubuntu 22.04 LTS AMI (Canonical)
# ------------------------------------------------------------------
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ------------------------------------------------------------------
# Networking — use the account's default VPC to keep this simple.
# ------------------------------------------------------------------
data "aws_vpc" "default" {
  default = true
}

resource "aws_security_group" "web" {
  name        = "${var.project_name}-web"
  description = "Allow SSH and HTTP/HTTPS to the app instances"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_ingress_cidr]
  }

  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "HTTPS"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Project = var.project_name
  }
}

# ------------------------------------------------------------------
# One EC2 instance per environment (nonprod, prod), each running nginx.
# ------------------------------------------------------------------
resource "aws_instance" "app" {
  for_each = toset(var.environments)

  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.deploy.key_name
  vpc_security_group_ids = [aws_security_group.web.id]
  iam_instance_profile   = aws_iam_instance_profile.app[each.key].name

  # Rendered so each environment's instance boots with the backend runtime
  # (KAN-31) pointed at ITS OWN Secrets Manager entries. user_data.sh embeds
  # the Node-install / systemd-unit / nginx-proxy provisioning logic directly
  # (kept byte-for-byte identical to infra/scripts/provision-backend.sh and
  # infra/systemd/crypto-tracker-backend.service — see the comments in
  # user_data.sh), which is also what deploy-backend-ec2.sh pushes over SSH
  # to already-running instances, so both paths configure the box the same
  # way. Only these 4 per-environment scalars are templated in.
  user_data = templatefile("${path.module}/user_data.sh", {
    environment     = each.key
    aws_region      = var.aws_region
    db_secret_name  = aws_secretsmanager_secret.db[each.key].name
    jwt_secret_name = aws_secretsmanager_secret.jwt[each.key].name
  })

  tags = {
    Name        = "${var.project_name}-${each.key}"
    Project     = var.project_name
    Environment = each.key
  }
}

# Elastic IPs so the public address is stable across stop/start.
resource "aws_eip" "app" {
  for_each = toset(var.environments)

  instance = aws_instance.app[each.key].id
  domain   = "vpc"

  tags = {
    Name        = "${var.project_name}-${each.key}"
    Environment = each.key
  }
}
